server:
  port: ${PORT:8080}
  servlet:
    context-path: ai
spring:
#  web:
#    resources:
#      static-locations: file:///Users/bm/intellijProjects/ollama-embedding-test/src/main/resources/static/
  thymeleaf:
#    prefix: file:///Users/bm/intellijProjects/ollama-embedding-test/src/main/resources/templates/
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:192.168.0.20}:${DB_PORT:5432}/${DB_SCHEMA:ollama-embedding-test} # schema ??? webflux? ???
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  ai:
    ollama:
      base-url: ${OLLAMA_ENDPOINT:http://192.168.0.4:11434}
  application:
    name: ollama-embedding-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:192.168.0.24}:${EUREKA_PORT:8081}/eureka/

logging:
  file:
    path: ./logs
  level:
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc: debug
    org.springframework.web.client: info


